### ISSUE TITLE
Support multiple instances in the same UA

### ISSUE THREAD

**Issue by wongchito** [railmapgen/rmg#40]
能否考虑保存上一个编辑的存档或更多？

_Originally posted by @3394946742 in #31_

- [x] Add unique ID for existing `param` and maintain `id <-> param` mapping in localStorage #463 
- [x] Remove style path param #464 
- [x] Add query parameter in RMG url to identify current `param` and add UI for selecting `param` #465 #466 
- [x] Replace single param registry to multiple param config #467 
- [x] Support switching param #468 
- [x] Error handling, editable project name, UI fixes #470 
- [x] Toggle on in PRD env #471

**Comment by wongchito** [comment]
Require #95

**Comment by thekingofcity** [comment]
Some thoughts on this feature. Will we implement real multiple saves or a fake one? A fake tab will be `unmount` and `renderApp` we did recently on #96. A real one requires a big change in the current redux store as we have to add another layer of selection.

I'm only discussing the runtime, not the storage where IndexedDB should suffice.
