### ISSUE TITLE
Modularise style-based SVG components

### ISSUE THREAD

**Issue by wongchito** [railmapgen/rmg#418]
- [x] Wrap every SVG component with `<SvgWrapper/>` individually instead of providing the wrapper in `<SvgRouter/>` to help RMG modularisation for simplifying new style contribution. #419 
- [x] Unify canvas-based stylesheet to single style-based stylesheet for each style to reduce related logic inside React component #419 
- [x] Segregate canvas definitions from SvgRouter #420
