### ISSUE TITLE
Support displaying facility icon in interchange lines

### ISSUE THREAD

**Issue by wongchito** [railmapgen/rmg#539]
Example: High Speed Rail, Disneyland Resort Line and Ngong Ping 360 interchanges on MTR Tung Chung Line map.

- [x] Extend current type `InterchangeInfo` to support facility input and make it more flexible (undefinable) railmapgen/rmg#540 
- [x] Update `param` based on the new type (toggled off) railmapgen/rmg#541
- [x] Update SVG components to support new fields #542 
- [x] Update Redux reducers to read/write new fields #542 
- [x] railmapgen/rmp#315
- [x] Remove legacy fields #542 
- [x] Add Ngong Ping 360 c759129
- [x] Display facility icon in interchanges f1715ef
